In [1]:
import numpy as np

In [55]:
x = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0,1,1,0]]).T


In [6]:
y.shape , x.shape

((4, 1), (4, 2))

In [8]:
def sigmoid(z):
    return 1/(1+ np.exp(-z))

In [25]:
def derivativeSig(z):
    return sigmoid(z)*(1-sigmoid(z)) 

In [49]:
#To make it lie between -1 and 1 we have multiplied the random no.(which wa b/w 0 &1) by 2
#and subtracted 1 from it 

#without hidden layer
weights = 2*np.random.random((2,1)) - 1
weights
bias = 2*np.random.random(1) - 1
bias
lr = 0.3


In [47]:
#We have done dot so as to get the matrix multiplication of the 2 matrix
for i in range(10000):
    output = sigmoid(np.dot(x,weights) + bias)
    output

    first_term = output - y
    second_term = derivativeSig(np.dot(x,weights) + bias)
    first_two = first_term * second_term
    first_two.shape

    last_layer_input = np.dot(x,weights) + bias
    changes = np.array([[0.0],[0.0]])
    bias_change = np.array([0.0])

    for i in range(2):
        for j in range(4):
            changes[i][0] += first_two[j][0]* x[j][i]


    for j in range(4):
        bias_change += first_two[j][0]* 1

    weights -= lr*changes
    bias -= lr*bias_change
    output = sigmoid(np.dot(x,weights) + bias)
weights
output
# last_layer_input.shapep9999

array([[3.81437133e-05],
       [3.07549279e-02],
       [3.07549279e-02],
       [9.63497071e-01]])

In [50]:
#A bit more optimized version of the above code
#We have done the matrix multiplication of the transpose of the input and weights
for i in range(10000):
    output = sigmoid(np.dot(x,weights) + bias)
    output

    first_term = output - y
    second_term = derivativeSig(np.dot(x,weights) + bias)
    first_two = first_term * second_term
    first_two.shape

    last_layer_input = np.dot(x,weights) + bias
    changes = np.dot(x.T,first_two)
    bias_change = np.sum(first_two)

    weights -= lr*changes
    bias -= lr*bias_change
output = sigmoid(np.dot(x,weights) + bias)
weights
output

array([[3.81713499e-05],
       [3.07621035e-02],
       [3.07621035e-02],
       [9.63488527e-01]])

In [74]:
#with hidden layers
wh = 2*np.random.random((2,2)) -1
bh = 2*np.random.random((1,2)) - 1
b0 = 2*np.random.random((1,1)) - 1
w0 = 2*np.random.random((2,1)) - 1
lr = 0.4

In [76]:
#NOw do the above things 2 times
for i in range(7000):
    output0 = x
    inputHidden = np.dot(output0,wh) + bh
    outputHidden = sigmoid(inputHidden)
    inputForOutputLayer = np.dot(outputHidden,w0) + b0
    output = sigmoid(inputForOutputLayer)
    first_term_output_layer = output - y
    second_term_output_layer = derivativeSig(inputForOutputLayer)
    first_two = first_term_output_layer * second_term_output_layer

    first_term_hidden_layer = np.dot(first_two,w0.T)
    second_term_hidden_layer = derivativeSig(inputHidden)
    first_two_hidden_layer = first_term_hidden_layer * second_term_hidden_layer

    changes_output = np.dot(outputHidden.T,first_two)
    bias_change_output = np.sum(first_two, axis =0 , keepdims= True)

    changes_hidden = np.dot(output0.T,first_two_hidden_layer)
    bias_change_hidden = np.sum(first_two_hidden_layer , axis = 0, keepdims = True)

    w0 -= changes_output*lr
    b0 -= bias_change_output*lr
    wh -= changes_hidden*lr
    bh -= bias_change_hidden*lr

output0 = x
inputHidden = np.dot(output0,wh) + bh
outputHidden = sigmoid(inputHidden)
inputForOutputLayer = np.dot(outputHidden,w0) + b0
output = sigmoid(inputForOutputLayer)
output
w0


array([[-9.27691087],
       [ 9.76208846]])